[Variables]
;Almost all variables ar Dynamic - best not to change them without prior knowledge of what they do

;Background size and pos
Height=60
Width=380
BGY=0
BGX=0

;Progress bar size and pos
SeekY=29
SeekX=140
SeekW=220

;Song title size and pos
TitleY=2
TitleX=138
TitleW=220
TitleSize=12

;Play button size and pos
PlayY=8
PlayX=23
PlaySize=32

;Hide button pos
BtnX=370

;Minimize/Maximize button pos
MinY=0

;Important! Do not change
OffY=0
Hide=0
Mini=0
Pause=0
MinBtn=plus
HideState=Hide
MinState=Minimize

;Marquee settings
animationSpeed=20
marqueeBeginWait=2000
marqueeEndWait=2000
marquee1=0
prevSong=N/A