[Variables]
;Almost all variables are Dynamic - best not to change them without prior knowledge of what they do

;Background size and pos
Height=60
Width=380
BGY=0
BGX=0

;Progress bar size and pos
SeekY=28
SeekX=139
SeekW=220

;Song title size and pos
TitleY=2
TitleX=138
TitleW=220
TitleSize=12

;Play button size and pos
PlayY=10
PlayX=30
PlaySize=20

;Hide button pos
BtnX=370

;Minimize/Maximize button pos
MinY=0

;Marquee settings
marquee1=0
 ; Higher is faster
animationSpeed=1
 ; How many ms to wait before starting to scroll forwards
marqueeBeginWait=2000
 ; How many ms to wait before starting to scroll backwards
marqueeEndWait=2000

;Important! Do not change
OffY=0
Hide=0
Mini=0
Pause=0
MinBtn=plus
HideState=Hide
MinState=Minimize
muteState=unmute
hover=0